### PR TITLE
Bug Report: CDI tries to instantiate interface (Jersey 2.30)

### PR DESCRIPTION
**Pull request by jbescos**
https://github.com/eclipse-ee4j/jersey/issues/4781

### CODE REVIEW

**Comment by senivam** [comment]
isn't it better to put ``FINE/FINER`` level output?

**Comment by jbescos** [comment]
> isn't it better to put `FINE/FINER` level output?

I thought it is too much to move from WARNING to FINE, but I am okay doing that.

**Review by senivam — APPROVED** [review]
LGTM

**Review by senivam — CHANGES_REQUESTED** [review]
actually 1 change is required:

the main IF here checks if resource is acceptable. Whis includes:
```
 ((c.getModifiers() & Modifier.ABSTRACT) != 0
                         || c.isPrimitive()
                         || c.isAnnotation()
                         || c.isInterface()
                         || c.isLocalClass()
                         || (c.isMemberClass() && (c.getModifiers() & Modifier.STATIC) == 0));
```
however as per the issue description this warning output is not applicable only to interface. 
So, it would be appropriate to write 
```
LOGGER.log( clazz.isInterface() ? Level.FINE : Level.WARNING,
                    LocalizationMessages.CDI_NON_INSTANTIABLE_COMPONENT(clazz));
```

**Comment by jbescos** [comment]
> actually 1 change is required:
> 
> the main IF here checks if resource is acceptable. Whis includes:
> 
> ```
>  ((c.getModifiers() & Modifier.ABSTRACT) != 0
>                          || c.isPrimitive()
>                          || c.isAnnotation()
>                          || c.isInterface()
>                          || c.isLocalClass()
>                          || (c.isMemberClass() && (c.getModifiers() & Modifier.STATIC) == 0));
> ```
> 
> however as per the issue description this warning output is not applicable only to interface.
> So, it would be appropriate to write
> 
> ```
> LOGGER.log( clazz.isInterface() ? Level.FINE : Level.WARNING,
>                     LocalizationMessages.CDI_NON_INSTANTIABLE_COMPONENT(clazz));
> ```

Correct, nice catch.

**Review by senivam — APPROVED** [review]

**Review by jansupol — APPROVED** [review]

**Pull request merged**
