### PR TITLE
Update JMockit from 1.18 to 1.24 to fix OpenJDK incompatibility

### PR DESCRIPTION
**Pull request by chkal**
Building the project from sources currently fails with OpenJDK:

```
java.lang.IllegalStateException: To run on OpenJDK 64-Bit Server VM use -javaagent:/home/ck/.m2/repository/org/jmockit/jmockit/1.18/jmockit-1.18.jar
	at org.apache.maven.surefire.junitcore.pc.ParallelComputerBuilder$PC.getSuite(ParallelComputerBuilder.java:296)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:97)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:89)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:58)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

This is caused by a known bug in JMockit 1.18 (see jmockit/jmockit1#196) which has been fixed in 1.19.

This pull request updates JMockit to 1.19.

### CODE REVIEW

**Comment by jansupol** [comment]
Why did you choose 1.19? Does it make sense to grab the latest jMockit?

**Comment by chkal** [comment]
I didn't want to make a "huge" update just to make sure to don't break anything else. And 1.19 fixed the original problem. But if you agree, I could update the PR to update to 1.39.

**Comment by chkal** [comment]
@jansupol I just checked version 1.39 of jMockit. Unfortunately with this version I'm running into a weird `StackOverflowError`:

```
[ERROR] java.lang.StackOverflowError
[ERROR] 	at mockit.internal.expectations.mocking.MockedBridge.invoke(MockedBridge.java:42)
[ERROR] 	at java.io.InputStream.<init>(InputStream.java)
[ERROR] 	at java.util.zip.ZipFile$ZipFileInputStream.<init>(ZipFile.java:711)
[ERROR] 	at java.util.zip.ZipFile.getInputStream(ZipFile.java:375)
[ERROR] 	at java.util.jar.JarFile.getInputStream(JarFile.java:447)
[ERROR] 	at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:977)
[ERROR] 	at sun.misc.Resource.cachedInputStream(Resource.java:77)
[ERROR] 	at sun.misc.Resource.getByteBuffer(Resource.java:160)
[ERROR] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
[ERROR] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[ERROR] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[ERROR] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[ERROR] 	at java.security.AccessController.doPrivileged(Native Method)
[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] 	at mockit.internal.expectations.mocking.MockedBridge.invoke(MockedBridge.java:42)
[ERROR] 	at java.io.InputStream.<init>(InputStream.java)
[ERROR] 	at java.util.zip.ZipFile$ZipFileInputStream.<init>(ZipFile.java:711)
[ERROR] 	at java.util.zip.ZipFile.getInputStream(ZipFile.java:375)
[ERROR] 	at java.util.jar.JarFile.getInputStream(JarFile.java:447)
[ERROR] 	at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:977)
[ERROR] 	at sun.misc.Resource.cachedInputStream(Resource.java:77)
[ERROR] 	at sun.misc.Resource.getByteBuffer(Resource.java:160)
```

So I guess updating to 1.19 should be preferred for now.

**Comment by mkarg** [comment]
@chkal Did you already file a CQ with the EMO regarding the Mockito version update?

**Comment by jansupol** [comment]
There is http://dev.eclipse.org/ipzilla/show_bug.cgi?id=16270 for jMockit. Not sure where it goes, jMockit contains classes from openjdk which are under GPLv2vCPE, for which we may need to switch to some other mocking library. Will see what the legal will ask us to do.

**Comment by senivam** [comment]
@chkal I've just checked the 1.41 version of JMockit to be compatible with Jersey running on openjdk version 1.8.0_40. It seems to work. At least several builds were completed OK. Could you please check that version as well. If it succeeds possibly we could use the newest version of JMockit.

**Comment by senivam** [comment]
@chkal After several tries on 2 Open JDKs (1.8.0_40 and 1.8.0_192-ea) I've discovered that the latest JMockit version which reliable passes on both is 1.24. Could you please check that on yours JDK as well?

**Comment by chkal** [comment]
@senivam I can confirm that 1.41 causes issues with OpenJDK 1.8.0_181. I just tried 1.24 and the JMockit related issues seems to be resolved. However, the full build is still not working on my box, but the error I'm getting now seems to be caused by another issue.

I updated my pull request to 1.24 and rebased against master. So let's see if the Travis build works.

**Comment by chkal** [comment]
Could someone perhaps restart the Travis build? The Travis CI server had [some issues yesterday](https://www.traviscistatus.com/incidents/118bjpkgkg00), so the build failed. Restarting it should fix the problem.

**Comment by mkarg** [comment]
@chkal Your recent push this morning restarted it (apparently Travis CI seems to be overloaded due to the outages of yesterday), but it proofs that we need to have a volunteer committer that can help out in such situations (i. e. on weekends). Maybe we should apply once our initial contributions are accepted. ;-)

**Comment by chkal** [comment]
@mkarg Yeah, we should apply at some point! ;-)

@senivam @jansupol I can confirm that the build works fine with OpenJDK8 now. And it works even on Travis. So I added `openjdk8` to the `.travis.yml`. Running the build against both OracleJDK8 and OpenJDK8 is a good way to ensure compatibility with both JDKs in the future.

**Comment by chkal** [comment]
Just a quick question! Do we need to create another CQ for JMockit 1.24 or is it covered by the [JMockit Version: 1.18 AND LATER Versions](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16270) CQ?

**Comment by senivam** [comment]
@chkal yes, the appropriate CQ shall be created. However just now I'm testing fixes in Jersey which should allow JMockit upgrade to the version 1.41. If all is fine (we can upgrade JMockit to 1.41) the CQ shall be created for that version.

**Comment by chkal** [comment]
@senivam Awesome! That's great new! I just wanted to create the corresponding CQ, but it looks like I'm not allowed to do so, because I'm not a Jersey committer. Or am I missing something?

**Comment by senivam** [comment]
@chkal I've managed to fix tests in Jersey so that they works with OpenJDK and JMockit 1.41. And I've done a pull request for this. Could you please take a look at the PR https://github.com/eclipse-ee4j/jersey/pull/3916 and modify your PR accordingly? Then (after CQ is approved) it (your version) will be merged ...

**Comment by chkal** [comment]
@jansupol Thanks for creating the CQ.

@senivam The PR looks great! But if #3916 gets merged, we can close this one. So there is no need to update it I guess.

**Pull request closed without merging**
