### PR TITLE
Added Travis CI.

### PR DESCRIPTION
**Pull request by Tomas-Kraus**
Another attempt which finally seems to work.

### CODE REVIEW

**Comment by mkarg** [comment]
@jansupol Is there a good reason for _neither_ commenting _nor_ reviewing this PR for 12 days by _any_ committer? As you know, over at JAX-RS API we have this 14-days-limit. It would be good if we can come to _frequent and prompt_ reviews in Jersey, too. If there are too few _active_ committers, @chkal and me can help out -- but we need to be committers then, certainly.

**Comment by Tomas-Kraus** [comment]
Markus, that's fine. We are still having some issues with Travis besause of its various limitations.
Unfortunately this version is still not working perfectly. But we are still trying to find some solution.
Also I'm sitting some 2 meters from Jan in the same office so don't worry, I have some good ways how to push him if really needed. :D

**Comment by mkarg** [comment]
@Tomas-Kraus Good to hear. In fact the question was not limited on this particular PR. I noticed that there are several PRs without comments / reviews and I wonder why.

**Comment by Tomas-Kraus** [comment]
This code is included in PR 3835 so let's close this one.

**Comment by chkal** [comment]
@jansupol @Tomas-Kraus 

> Also I'm sitting some 2 meters from Jan in the same office so don't worry, I have some good ways how to push him if really needed. :D

I absolutely understand that you are communicating a lot directly if you are in the same office. However, there are a lot of people who want to help and want to start contributing. And it feels weird that there is some kind of developing happening behind the scenes without any public communication. That's why [I already asked](https://github.com/eclipse-ee4j/jersey/issues/3816#issuecomment-388121185) if there is some other communication channel used by the committers. There are currently 32 committers listed on the Eclipse Jersey page. And I guess not all of them are in the same office.

Don't get me wrong. I really appreciate the work you are doing. But it would be great if the community could participate more.

**Comment by Tomas-Kraus** [comment]
Community has this available as PR 3835 - there are diffs and comments. We would like to see all of you helping us to move forward.
But at this stage it's not that easy. We don't have even basic CICD things like PR checks working.
So first of all we need to get those things up to make sure that every PR passes build, tests, coding style and other checks. Then we can start processing other things.

**Comment by mkarg** [comment]
Agreed in general, but in this special case Christian maybe could be helpful. He set up the Travis stuff for JAX-RS API recently.

**Comment by mkarg** [comment]
Proposal: (A) I could talk to the Travis guys, maybe they allow the Eclipse Foundation to use larger limits on STDOUT size and execution time. (B) Maybe "mvn -T 2C" will speed up processing, as Maven is rather I/O intensive, hence, its default sole thread blocks most of the time.

**Comment by Tomas-Kraus** [comment]
(A) would be great. If you have an option to ask for it, please give it a try. (B) making it even more parallel when there is already enough I/O load may make it worse. But I have no idea what's the default for -T and we won't loose anything with giving it a try.

**Comment by Tomas-Kraus** [comment]
Challenge accepted. :) Jersey tests are not best candidate at this moment because of server ports. But we have a lot of other projects with clean junits where it makes sense.

**Comment by mkarg** [comment]
@Tomas-Kraus The Travis CI guys told me they will soon extend Jersey's timeout to 3 hours. Is this long enough? They cannot make it larger than that. They also do not have a STDOUT length limitation but say that there is a timeout limitation that stops logging; they also extend it to 3 hours. Let's see if this helps. They agreed to do this change for all projects I name them. So if it helps please let me know so I can ask the PMC if others had similar issues. Shall I ask them if they can set up a facility for data only images?

**Comment by Tomas-Kraus** [comment]
The only problem I currently know about is Jersey. It will be great if they can extend stdout timeout to 3 hours for it. Another big projects are glassfish (not yet donated) and eclipselink.
Now the Docker things. EclipseLink and Jersey builds can be optimized if I can do
- build without tests first 
- and then use it to run matrix of tests using several isolated instances of already built sources
Data only image is a good way to achieve this. But I also need tools to build such an image using docker and create container from it and link it as java/ant/maven container directory.

With EclipseLink situation is even more complicated because we need to test it with matrix of databases. I use set of Docker images with various databases to do it.
So typical EclipseLink Docker setup are 3 containers linked togeher:
- built sources (instance of data only image)
- java/ant/maven/... environment
- database (MySQL, Oracle, Derby, DB2, ...)

Without data only image we have to clone and build project in each of the container which is just wasting of resources.

**Comment by mkarg** [comment]
@Tomas-Kraus Regarding the idea of compiling once, storing the binaries and then running the tests I would say that this is possible. You need [Build Stages (BETA)](https://docs.travis-ci.com/user/build-stages/) with a first stage doing mvn -DskipTests=true install and then storing to a cache. The second (parallel) stages will run the tests using the binaries stored in the cache. If you need multiple caches, you can name them. For larger data to be shared, there is an [example using S3](https://docs.travis-ci.com/user/build-stages/share-files-s3/). If you need help with this, I can forward the Travis guy to you, but I doubt that he will mount docker data volumes. Maybe I miss something, by why shouldn't that work?

**Comment by Tomas-Kraus** [comment]
I can give it a try. If there are stages and it's possible to pass sources tree and maven repo between them, there is a chance that it may work.
I'm quite busy those days, but I can try some sample to understand how it works.

**Comment by Tomas-Kraus** [comment]
I was doing some experiments on https://github.com/Tomas-Kraus/jsonp
The small hack I did is in adding $HOME/build into cache directories. It breaks git so I have to update branch and revision manually, but is seems to work.
In this case it would be nice to disable git in 2nd stage where whole soource tree is restored from cache. But I have no idea how.

**Pull request closed without merging**
