### PR TITLE
allow for resource methods to return <? extends XYZ>

### PR DESCRIPTION
**Pull request by jansupol**

### CODE REVIEW

**Comment by mkarg** [comment]
Thank you for fixing this! :+1:

**Review by mkarg — APPROVED** [review]
Thanks! :-)

**Review by senivam — APPROVED** [review]

**Comment by mkarg** [comment]
You are awesome, guys! Really begging to get this feature ASAP! :-)

**Comment by mkarg** [comment]
What is the schedule for getting this change into a release?

**Comment by mkarg** [comment]
Thank you Maxin, for the outlook, but actually I need to know the schedule for 3.x. I assume that would happen shortly after?

**Comment by senivam** [comment]
usually yes, but it depends on the number of changes to be released.

**Comment by mkarg** [comment]
In Jersey 2.x, when an InterceptorWriter was replacing a Collection's **content** (e. g. from `Collection<Apple>` to `Collection<Banana>`) *solely setting the entity* by `context.setEntity(myCollection)` (hence, *no* `context.setGenericType()` was used), then the type of the objects inside of the collection was correctly detected to be `Banana`, not `Apple` anymore. Since Jersey 3.x, Jersey forwards the *old* type, so `Apple` is still expected, leading to Yasson being unable to cast `Banana` to `Apple`.

Will this PR *also* resolve *that* problem, too, or is the WriterInterceptor required to *also* `context.setGenericType()`?

**Review by jbescos — APPROVED** [review]

**Comment by ar30067** [comment]
in class ResourceMethodValidator.java Line 134 
`
 final Type responseType = invocable.getResponseType();
        if (!isConcreteType(responseType)) {
            Errors.warning(invocable.getHandlingMethod(),
                    LocalizationMessages.**TYPE_OF_METHOD_NOT_RESOLVABLE_TO_CONCRETE_TYPE**(responseType,
                            invocable.getHandlingMethod().toGenericString()));
        }
`
is this warning related to this issue ?

**Comment by jansupol** [comment]
@ar30067 It may be in case your resource methods return <? extends XYZ>  or may not if the cause is different.

**Pull request merged**
