### PR TITLE
Support for SSL Configuration within JerseyTest

### PR DESCRIPTION
**Pull request by Hakky54**
This PR should resolve the following issue: https://github.com/eclipse-ee4j/jersey/issues/4572

On stackoverflow, https://stackoverflow.com/q/63924572/6777695 , someone has asked a question to configure the server with ssl and while helping the person I discovered this feature was missing within the JerseyTest. This PR should enable the developer to create a JerseyTest with a custom SSL/TLS configuration.

It can for example be enabled with the following method override:

```java
// SSLContext sslContext;
// boolean clientMode;
// boolean needClientAuth;
// boolean wantClientAuth;

@Override
protected Optional<SSLEngineConfigurator> getSslEngineConfigurator() {
        return Optional.of(new SSLEngineConfigurator(
                    sslContext,
                    clientMode,
                    needClientAuth,
                    wantClientAuth
            ));
}
```

This pull request will close the following issue: https://github.com/eclipse-ee4j/jersey/issues/4572

### CODE REVIEW

**Comment by jansupol** [comment]
At first glance, the PR looks wrong. The added hard dependency on grizzly in the independent Jersey test module cannot be accepted; while grizzly might be the most common backend for testing, there are many who use other backend.

**Comment by Hakky54** [comment]
The main reason why I added grizzly-framework is to make the SSLEngineConfigurator available within JerseyTest. The two backends GrizzlyTestContainerFactory and GrizzlyWebTestContainerFactory can use that object in that way directly. But I wasn't aware that end-users also are able to use other backends and that would indeed make option not usable for their needs.

What do you think of adding support for SSLContext within the DeploymentContext instead of the SSLEngineConfigurator. In that way the backend can have his own adapter to translate it. GrizzlyTestContainerFactory and GrizzlyWebTestContainerFactory can use the SSLContext and create an instance of SSLEngineConfigurator and supply it to the Grizzley Server and other backend will have their own implementation.

**Comment by Hakky54** [comment]
Hi @jansupol 

I tried to resolve your concerns. I removed the hard dependency on grizzly and instead of supplying the ssl configuration with SSLEngineConfigurator it is now working with SSLContext and SSLParameters. The enduser needs to override two methods to enable the ssl configuration:

```java
@Override
protected Optional<SSLContext> getSslContext() {
    SSLContext sslContext = ...; // initialized SSLContext
    return Optional.of(sslContext);
}

@Override
protected Optional<SSLParameters> getSslParameters() {
    SSLParameters sslParameters = new SSLParameters();
    sslParameters.setNeedClientAuth(true);
    return Optional.of(sslParameters);
}
```

Although not all properties are being picked up from the sslParameters while configuring for example grizzly it can if it will support additional configuration in the future. If such changes happens to support for example custom list of ciphers or protocols the JerseyTest doesn't needs to be adjusted as it can already hold these properties with SSLParameters object.

What do you think of this adjusted pull request, is it more according to what you would apply or do you think we should drop it for now?

**Comment by Hakky54** [comment]
@senivam or @jansupol I was wondering what the status of this pull request is. Would you like me to adjust something else or add something what you think is still missing?

**Comment by jansupol** [comment]
Sorry for the delay. We have been focused on other urgent tasks. This PR looks much better than the original one. Would you mind to update the copyright years to 2020? Thank you.

**Comment by Hakky54** [comment]
Yes, just added it. Let me know if something else needs to be done

**Comment by jansupol** [comment]
Ooops, only the files you actually changed were supposed to have copyright year adjusted. Not all of them...

**Comment by Hakky54** [comment]
Aha, thats pity. Let me quickly revert it and only change those specific files

**Comment by Hakky54** [comment]
@jansupol fixed!

**Review by jansupol — APPROVED** [review]
Looks good, thank you

**Comment by Hakky54** [comment]
Hi @jbescos Would you also like to review this pull request, what is your opinion on it?

**Review by jbescos — COMMENTED** [review]
Could you create one unit test where you can test this change?.

**Comment by Hakky54** [comment]
@jbescos Good suggestions! I have added unit tests to cover 5 scenarios both happy and unhappy flows.
I also included a test library, however I wasn't quite sure if you guys would be okay with me adding my own library as a test scoped dependency into this sub module. It makes it a-lot easier to create a SSLContext for all these scenarios.

And I am curious if you have other feedback or other additional tasks what I can do for this pull request to improve it.

**Comment by Hakky54** [comment]
Hi @jbescos I added some unit tests to cover happy as well as unhappy flows. The tests passes, could you have another look at it?

I also added my [own library](https://github.com/Hakky54/sslcontext-kickstart) as a test library to create a SSLContext for the server and client and the main reason was to easily create the ssl material without the need of introducing a-lot additional code/complexity into the code base. I was not quite sure if would be okay with that, so what do you think about it?

**Comment by jbescos** [comment]
@Hakky54 looks good to me, but I am not sure we can introduce third party libs without some sort of discussion.
As it is in test scope maybe it is not necessary, but honestly I don't know. I wanted to drop the attention of @jansupol to check that.

**Comment by jansupol** [comment]
Every 3rd party dependency needs to go through a legal review. The legal reviews every file whether it contains the license header. Since this lib does not contain the license header in the source files, I am not sure whether the lib would be approved, the process might get complicated. Is it a big deal not to use the lib?

**Comment by Hakky54** [comment]
I didn't know that every 3rd party dependency would have to go through a legal review, but I can understand that would be time consuming. The library is not a must have for the unit test to be working, but a nice to have to prevent additional custom code into the code base. And I was very enthusiastic to add my own library into it 😄 

I have removed library and added a very minimalistic SslUtils to build the SSLContext. The unit test passes with the latest changes. Could you guys review it again? Anything what should be adjusted or done differently in your opinion?

**Review by jansupol — APPROVED** [review]
Looks better than ever.

**Review by senivam — APPROVED** [review]

**Comment by Hakky54** [comment]
Thank you very much for spending this much time for reviewing, approving and merging this pull request. I feel very honoured to contribute to the Jersey project 😊

**Pull request merged**
