### PR TITLE
Regexp on MP RestClient @Path

### PR DESCRIPTION
**Pull request by mcserra**
Solves #4348 
Signed-off-by: Miguel Serra <Miguel.Serra@criticaltechworks.com>

### CODE REVIEW

**Comment by senivam** [comment]
Thanks for the PR. First of all I would like you take a look at Check Style notifications (in failed build on travis) and copyright year/headers adjustments. And also I would like to ask @Verdent to take a look at the PR.

**Comment by mcserra** [comment]
Thanks. I made the changes and the build still failed, but the error is not related to my changes, I guess

**Comment by senivam** [comment]
@mcserra now it's only technical issue, build will pass, thank you for fixes.

**Comment by senivam** [comment]
@mcserra please consider accepting PR to your branch [1](https://github.com/mcserra/jersey/pull/1), after that this PR can be merged

**Comment by mcserra** [comment]
Done! Thanks

**Pull request merged**
