### PR TITLE
Update hk2 osgi-resource-locator to latest 1.0.3 version

### PR DESCRIPTION
**Pull request by jansupol**
Signed-off-by: Jan Supol <jan.supol@oracle.com>

### CODE REVIEW

**Comment by Cousjava** [comment]
Why is a CQ required? HK2 is an eclipse project.

**Comment by jansupol** [comment]
@Cousjava 
HK2 is, but it requires `org.osgi.framework;version="1.8"` for which we need to update `org.osgi:org.osgi.core`, `org.osgi:org.osgi.compendium`, `org.apache.felix:org.apache.felix.framework`. These are apache projects.

**Comment by jansupol** [comment]
Filed CQs:
- [CQ 19391 - OSGi Core 6.0](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=19391)
- [CQ 19392 - OSGi Compendium 5.0](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=19392)
- [CQ 19393 - Apache Felix Framework 5.0.1](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=19393)

**Comment by jansupol** [comment]
The CQs were approved

**Pull request merged**
