### PR TITLE
Eclipse J2EE superpom

### PR DESCRIPTION
**Pull request by senivam**
Common super-pom for eclipse-j2ee projects 

Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

### CODE REVIEW

**Comment by bshannon** [comment]
What is this "J2EE" thing you're talking about?  :-)

**Comment by Tomas-Kraus** [comment]
LOL :) Anyway, it was not mentioned in the sources so there was no reason to refuse the changeset.
@arjantijms: As far as I remember, whole Sun was always talking about J2EE.

And now something real to solve: org.eclipse.ee4j : project : 1.0.1 is in maven central so it's time to update this pom too.

**Comment by jansupol** [comment]
Suppose it takes time for an old dog to learn new tricks....

**Comment by arjantijms** [comment]
Lol, ok. Btw, it can be updated to 1.0.1 right away, as that one was just released.

**Comment by senivam** [comment]
sorry guys, as you understand that is pure optical illusion. You see J2EE but in fact that is EE4J. 

I've updated the superpom's version to 1.0.1

**Comment by arjantijms** [comment]
>sorry guys, as you understand that is pure optical illusion. You see J2EE but in fact that is EE4J.

Ah, now it makes sense ;)

>I've updated the superpom's version to 1.0.1

👍

**Pull request merged**
