### PR TITLE
new InvocationBuilderListener SPI

### PR DESCRIPTION
**Pull request by jansupol**
Signed-off-by: Jan Supol <jan.supol@oracle.com>

### CODE REVIEW

**Comment by jansupol** [comment]
This new SPI interface allows for 
- creating decorators that modify the requests (`Invocation.Builder`) as needed.
- setting the ClientRequestContext properties (in the main thread rather than in the executor service thread when invoked by RxInvoker and set by Filter), possibly registered automatically using `AutoDiscoverable` interface
- providing functionality already requested by the MP [RestClientBuilderListener](https://github.com/eclipse/microprofile-rest-client/blob/master/api/src/main/java/org/eclipse/microprofile/rest/client/spi/RestClientBuilderListener.java)

**Comment by jansupol** [comment]
@pdudits Would this help you with #4267?

**Comment by jansupol** [comment]
@pdudits The `InvocationBuilderListener` is to be called when the `InvocationBuilder` is created, the same as the `RestClientBuilderListener`. Is it good enough for you to have it called at the time, i.e. long time before the `rx()` is called?

**Comment by pdudits** [comment]
I'll have a detailed look tomorrow, at first sight it looks good. One usually uses RestClientBuilder to build client for many invocations (in real applications, contrary to tests), so I think the relation of lifecycles are but different

**Comment by pdudits** [comment]
I tested this API with the same four usecases as in #4301, code is in [this branch](https://github.com/pdudits/patched-src-jersey/commits/pr-4313-experiments).

All of these usecases are satisfied by this, so I'm quite happy.

**Comment by jansupol** [comment]
@tomas-langer I have added getters to the headers, configuration, and URI.

**Pull request merged**
