### PR TITLE
Dependencies versions update (master)

### PR DESCRIPTION
**Pull request by senivam**
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

### CODE REVIEW

**Review by jbescos — APPROVED** [review]

**Comment by senivam** [comment]
org.jboss.arquillian.testng:arquillian-testng-container:1.5.0.Final [CQ24197](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24197) 
org.jboss.arquillian.container:arquillian-container-test-spi:1.5.0.Final [CQ24198](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24198)
org.jboss.arquillian.container:arquillian-weld-embedded:2.1.0.Final [CQ24200](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24200)

**Comment by senivam** [comment]
com.fasterxml:classmate:1.5.1 [CQ24209](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24209)
org.apache.felix:org.apache.felix.eventadmin:1.6.4 [CQ24210](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24210)
org.apache.felix:org.apache.felix.framework.security:2.8.3 [CQ24211](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24211)
org.apache.felix:org.apache.felix.framework:7.0.5 [CQ24212](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24212)
org.freemarker:freemarker:2.3.31 [CQ24213](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24213)
com.google.appengine:appengine-api-1.0-sdk:1.9.98 [CQ24214](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24214)
io.helidon.config:helidon-config:jar:1.4.9 [CQ24215](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24215)
org.javassist:javassist:3.29.0-GA [CQ24216](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24216)
org.jboss.logging:jboss-logging:3.5.0.Final [CQ24217](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24217)
org.openjdk.jmh:jmh-core:1.35 [CQ24219](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24219)
org.openjdk.jmh:jmh-generator-annprocess:1.35 [CQ24220](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24220)
org.junit.jupiter:junit-jupiter:5.9.0 [CQ24221](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24221)
org.junit.jupiter:junit-jupiter-engine:5.9.0 [CQ24222](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24222)
com.github.spullara.mustache.java:compiler:0.9.10 [CQ24223](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24223)
io.netty:netty-all:4.1.79.Final [CQ24224](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24224)

**Comment by senivam** [comment]
io.opentracing:opentracing-api:0.33.0 [CQ24225](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24225)
org.reactivestreams:reactivestreams:1.0.4 [CQ24226](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24226)
io.reactivex:reactivex:1.3.8 [CQ24227](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24227)
io.reactivex.rxjava2:rxjava:2.2.21 [CQ24228](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24228)
io.smallrye:smallrye-config:1.3.11 [CQ24229](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24229)
org.springframework:spring-web:4.3.30.RELEASE [CQ24230](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24230)
org.springframework:spring-beans:4.3.30.RELEASE [CQ24231](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24231)
org.springframework:spring-core:4.3.30.RELEASE [CQ24232](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24232)
org.springframework:spring-context:5.3.22 [CQ24233](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24233)
org.springframework:spring-beans:5.3.22 [CQ24234](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24234)
org.springframework:spring-core:5.3.22 [CQ24235](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24235)
org.springframework:spring-web:5.3.22 [CQ24236](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24236)
org.springframework:spring-aop:5.3.22 [CQ24237](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24237)
org.testng:testng:7.6.1 [CQ24238](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24238)
org.testng:testng:6.9.13.6 [CQ24239](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24239)

**Comment by senivam** [comment]
org.hibernate.validator:hibernate-validator:6.2.3.Final [CQ24240](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24240)
org.hibernate.validator:hibernate-validator:6.2.4.Final [CQ24241](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24241)
org.hibernate.validator:hibernate-validator-cdi:6.2.4.Final [CQ24242](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24242)
org.jboss.weld.se:weld-se-core:3.1.9.Final [CQ24243](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24243)
org.jboss.weld.servlet:weld-servlet:3.1.9.Final [CQ24244](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24244)
om.github.tomakehurst:wiremock:2.27.2 [CQ24245](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24245)

**Review by jansupol — APPROVED** [review]

**Pull request merged**
