### PR TITLE
Groovy jdk 16

### PR DESCRIPTION
**Pull request by senivam**
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

### CODE REVIEW

**Comment by senivam** [comment]
preparing gmaven-plus maven plugin including org.codehaus.groovy:groovy:4.x dependency to support JDK 16

**Review by jbescos — APPROVED** [review]

**Comment by jansupol** [comment]
Groovy 4.0 has [changed the maven artifact](http://groovy-lang.org/releasenotes/groovy-4.0.html) to org.apache.groovy and alpha-2 is in central.

**Comment by senivam** [comment]
created CQ for changed dependency: CQ [22957](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22957)

**Comment by senivam** [comment]
CQ ~~[22957](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22957)~~ resolved

**Review by jansupol — APPROVED** [review]

**Pull request merged**
