### PR TITLE
Replaced internal Base64 by java.util.Base64 (#3803)

### PR DESCRIPTION
**Pull request by mdurawa**
Using java.util.Base64 instead of core-common.src.main.java.org.glassfish.jersey.internal.util.Base64 allows to encode and decode characters > ASCII 127 (e. g. German umlauts).

### CODE REVIEW

**Comment by srbala** [comment]
@mdurawa Add test method to validate #3803 issue.

**Comment by mdurawa** [comment]
@srbala the tests are already there.
I updated core-common/src/test/java/org/glassfish/jersey/internal/util/Base64Test.java (it's the test class for the deleted class - maybe that could be marked as deprecated and removed in a future release):

As mentioned in the issue these tests checked that non Ascii 127 characters are not supported, I don't know the reason for this. Now they are fine with those characters/bytes.

- testRoundtripOneByteGreaterThan127()
- testRoundtripAssortedValues()
- testEncodeByteArray()

**Comment by jansupol** [comment]
I am not sure why the IP validation check did not take place here, but I do not see the sign-off. Can you please resubmit with -s ? Otherwise it looks good. Thanks

**Comment by mdurawa** [comment]
After some error messages on the client side, the sign-off message seems to be in the repository.

**Comment by mdurawa** [comment]
How can I fix the test of e2e-entity?
I get the same error with a clean copy of the project master.

**Pull request merged**
