### PR TITLE
Version of JMockit updated to 1.41

### PR DESCRIPTION
**Pull request by senivam**
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

### CODE REVIEW

**Comment by chkal** [comment]
Looks like there was some kind of temporary error with the build:

```
Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: http://repo.maven.apache.org/maven2/org/glassfish/pfl/pfl-basic-tools/4.0.0-b003/pfl-basic-tools-4.0.0-b003.jar. Return code is: 503 , ReasonPhrase:Service Unavailable.
    at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData (AbstractHttpClientWagon.java:1023)
    at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData (AbstractHttpClientWagon.java:962)
    at org.apache.maven.wagon.StreamWagon.getInputStream (StreamWagon.java:126)
    at org.apache.maven.wagon.StreamWagon.getIfNewer (StreamWagon.java:88)
    at org.apache.maven.wagon.StreamWagon.get (StreamWagon.java:61)
    at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run (WagonTransporter.java:567)
    at org.eclipse.aether.transport.wagon.WagonTransporter.execute (WagonTransporter.java:435)
    at org.eclipse.aether.transport.wagon.WagonTransporter.get (WagonTransporter.java:412)
```

So I guess you could simply restart it. This should be possible [here](https://travis-ci.org/eclipse-ee4j/jersey/builds/415846541).

**Comment by jansupol** [comment]
continuation of #3815

**Comment by chkal** [comment]
Great! Looks like restarting the job fixed the problem!

**Comment by senivam** [comment]
according to the last note in CQ 17250 (which was raised to comply JMockit version update to 1.41) we can use the latest version of JMockit based on the resolution of the CQ 16270 which relates JMockit of version 1.18 AND LATER. So, CQ 17250 is redundant and can be withdrawn. This PR thus can be merged.

**Comment by jansupol** [comment]
@senivam the cq is not redundant! The later versions is not for our product as described in the cq

**Comment by senivam** [comment]
@jansupol do not see how this excludes our products from later versions. What I see in comments to the CQ 16270 is 

> Processing Workswith - this Workswith has been resolved for other ee4j projects
> as well!

however this statement actually proves CQ for Jersey and other ee4j products.  Could you please clarify?

**Pull request merged**
