### PR TITLE
Issues 3753 - CDI2 doesn't work with BeanValidation

### PR DESCRIPTION
**Pull request by pa314159**

### CODE REVIEW

**Comment by pa314159** [comment]
After fighting with Travis failures, I decided to mark this PR ready for review anyway...

There are failures that don't seem to be related to my changes like this one

    https://travis-ci.org/pa314159/jersey/jobs/578705341

All tests pass on my systems, any idea? @mkarg?

**Comment by senivam** [comment]
I would advice to rebase this PR on current master. I could help resolve failing tests. 
The PR won't be merged until all checks are passed.

**Comment by jansupol** [comment]
@pa314159 Do you have any plans to continue with this? It looks rather messy, perhaps a rebase would be needed

**Comment by pa314159** [comment]
@jansupol I rebased several times so far.

As you can see, the test continues to fail, but I am not able to reproduce the issue, I have an app that works very well.

I think I will close this PR and wait for better times.

**Comment by mkarg** [comment]
> I think I will close this PR and wait for better times.

What do you mean by that? You hope somebody else will fix it?

**Comment by pa314159** [comment]
@mkarg, there is nothing I can fix as long as I cannot reproduce the issue locally...

**Pull request closed without merging**
