### PR TITLE
Race condition

### LINKED ISSUE #5358: Race condition
When the first GET request is in progress, all parallel requests from other Jersey clients, in other threads, fail with **SSLHandshakeException: PKIX path building failed**. 
Once the first GET request is completed,  all subsequent requests work without error.
Here is the code which demonstrates this issue:
https://github.com/dtbaum/jersey-bug-report

The fix in HttpUrlConnector.java solved the issue, see pull request https://github.com/eclipse-ee4j/jersey/pull/5359.
Affected versions: at least 3.1.2 & OpenJDK17 and 2.37 & OpenJDK 8

### PR DESCRIPTION
**Pull request by dtbaum**
Fixed race condition, see:
 https://github.com/eclipse-ee4j/jersey/issues/5358

### CODE REVIEW

**Comment by jansupol** [comment]
@dtbaum Can you please elaborate on how the race condition happens?

**Comment by dtbaum** [comment]
@jansupol The race condition occurs when multiple independent Jersey client instances, running in parallel threads, make a GET request. 

When the first GET request is in progress, all parallel requests from other Jersey clients (other client instances, but same SSLContext and same target), in other threads, fail with SSLHandshakeException: PKIX path building failed.
The first caller uses the correct trust store (which is defined in used SSLContext), the parallel callers use the java default trusstore.. The problem is not working `if (DEFAULT_SSL_SOCKET_FACTORY.get() == suc.getSSLSocketFactory())` condition. For subsequent requests it returns suc.getSSLSocketFactory() default factory, BUT another object reference to default factory, therefore the reference equality doesn't work here. A deep equality check, like working .equals() or removing the condition would solve it. 
Once the first GET request is completed, all subsequent requests work without error.
Here is the code which demonstrates this issue:
https://github.com/dtbaum/jersey-bug-report

If you get any issues getting the example to run, please let me know. I would add it as a broken JUnit test on this jersey branch.

**Comment by dtbaum** [comment]
@jansupol: Did you succeed in reproducing the problem?
The reason for the exception is following: Due to mentioned reference equality check,  the "parallel" threads do not use the specified SSLContext, but the default SSLContext  instead. 
Consequently, the server certificate validation occurs **not against the specified truststore**, but against the default truststore, leading to the mentioned exception.

**Comment by jansupol** [comment]
Thank you for the reproducer @dtbaum. The fix breaks `SslHttpUrlConnectorTest.testSSLWithCustomSocketFactory`, but we'll check if there is any possible fix for it.

**Comment by jansupol** [comment]
Related #4815 

This bug has a long history. Basically, there is a bug in JDK that we try to workaround, but there seem to be multiple requirements that go against each other.

**Comment by dtbaum** [comment]
@jansupol:  As much as I understand (which isn't much :-) ) a deep, reliable equality check, like working .equals() instead of object reference equality, would help, without violating other requirements?

**Comment by dtbaum** [comment]
@jansupol:  I think, I have a fix for the race condition, without violating #4757/#4566.  
I have made the method HttpUrlConnectorProvider.ConnectionFactory.getConnection() thread-safe: 
This ensures that parallel initialization in the HttpsURLConnection.getDefaultSSLSocketFactory()  is avoided.
See the screenshot below for call hierarchy:
image

**Review by jansupol — APPROVED** [review]

**Review by senivam — APPROVED** [review]

**Comment by fwippe** [comment]
@senivam @jansupol @dtbaum Please note that this change has been having a drastic impact on performance, in particular when using Jersey client for multiple services: Only one connection can be created at a time, across all routes. If the intention had been to just synchronize `HttpsURLConnection.getDefaultSSLSocketFactory()`, as an alternative you could have introduced a lazy one-off supplier initializing the socket factory. See #5738 for performance impact in practice.

**Pull request merged**
