### PR TITLE
When matching ParamConverter is found for given object in queryParam …

### PR DESCRIPTION
**Pull request by dabla**
…or matrixParam then object is converted to a String instead of simply invoking the toString method on the object (#4315)

Signed-off-by: David Blain <info@dabla.be>

### CODE REVIEW

**Comment by jansupol** [comment]
I wonder if `JerseyWebTarget` is the right place to utilize `ParamConverter`. That would be used just on the client.

Would it be better to use `ParamConverters` in `JerseyUriBuilder`? Pass the configuration to the `JerseyUriBuilder` and utilize the `ParamConverters` there. Then the `RuntimeDelegateDecorator` could pass the config to the `JerseyUriBuilder` instance and the `ParamConverter` could be used later on the server side, too.

**Comment by dabla** [comment]
> I wonder if `JerseyWebTarget` is the right place to utilize `ParamConverter`. That would be used just on the client.
> 
> Would it be better to use `ParamConverters` in `JerseyUriBuilder`? Pass the configuration to the `JerseyUriBuilder` and utilize the `ParamConverters` there. Then the `RuntimeDelegateDecorator` could pass the config to the `JerseyUriBuilder` instance and the `ParamConverter` could be used later on the server side, too.

True, that's what we also discovered today, as the ParamConverters for @PathParams are also ignore by the JerseyClient ,those could only be converted in the UriBuilder.  Will do an additional commit and move it to UriBuilder.

**Comment by dabla** [comment]
Question: Is it allowed to use assertj instead of Junit asserts and to upgrade Mockito?

**Comment by jansupol** [comment]
> Question: Is it allowed to use assertj instead of Junit asserts and to upgrade Mockito?

Generally, I am not a big fan of mocking frameworks. With JDK making the reflection usage harder, the newer versions of the mocking frameworks may have bigger requirements. We saw that with JMockit, which first required the agent to be run and then it stopped mocking the java.util classes. The agent defined in the pom file then is executed for every test, not just the mocked ones, which made the debugging harder as the agent came into action quite often. We had to separate the tests using Jmockit into a separate module. Not sure what the future of Mockito would be, but I'd better stay safe. For many use cases, JDK proxy is a fine replacement with just a couple of additional lines.

Regarding the new dependencies, add them only when necessary. First, each of them needs to be approved by the legal process, for each never version that is about to be used. Second, they potentially can bring a security vulnerability which we need to deal with ASAP, usually.

**Comment by dabla** [comment]
I see that for the latest commit, following test is failing, dunno how to fix this one :-(

FeatureConstraintTest.test:164 ClientSever Features should have been configured
Expected: is <11110>
     but: was <22110>

**Pull request closed without merging**
