### PR TITLE
JAX-RS 2.1.2 (Jakarta Maven Coordinates)

### PR DESCRIPTION
**Pull request by mkarg**
Using JAX-RS 2.1.2 (i. e. Jakarta Maven Coordinates) instead of JAX-RS 2.1 (i. e. javax Maven Coordinates).

### CODE REVIEW

**Comment by mkarg** [comment]
@jansupol Review please. :-)

**Comment by mkarg** [comment]
@jansupol Oops, Travis failed, seems I forgot something. Will check that, certainly. Sorry.

**Comment by jansupol** [comment]
@mkarg As I understand it, currently a discussion about the module names is going on. It is possible that a new module name should be used in API jars, which could result in a an actual need of releasing new version of API (again)

**Comment by mkarg** [comment]
@jansupol Jan, I am giving up. I have no clue why the OSGI test fails. To not lose more time on the critical path to GlassFish's integration in November, I'd like to ask you for help. Can you please check why this PR fails? Thanks.

**Comment by jansupol** [comment]
Closing this in favor of #3991

**Pull request closed without merging**
