### PR TITLE
Bump JAXB from 3.0.X to 4.0.X

### PR DESCRIPTION
**Pull request by hs536**
For Jakarta EE 10, it need to adapt to JAXB 4.0 incompatibility.  
Signed-off-by: hs536 <sawamura.hiroki@fujitsu.com>

### CODE REVIEW

**Comment by jansupol** [comment]
Thank you for the PR. Please update the copyright year to 2022.

**Comment by hs536** [comment]
Jenkins CI is still in error, I'll try to find out why.

**Comment by hs536** [comment]
These look like complex challenges to me.. To update to JAXB4, MOXy also needs to be updated. but the impact of these module incompatibilities seems to be greater than I thought.

**Comment by jansupol** [comment]
@hs536 I grabbed your changes and put them to #5008.

**Pull request closed without merging**
