### PR TITLE
Jakarta EE namespace transition

### PR DESCRIPTION
**Pull request by jGauravGupta**
Fixes: https://github.com/eclipse-ee4j/glassfish/issues/23016

Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>

### CODE REVIEW

**Comment by arjantijms** [comment]
See also https://github.com/eclipse-ee4j/jersey/pull/4468

**Comment by senivam** [comment]
I've merged this PR into mine (#4468), will fix tests and it will go to release M3 of Jersey. Presumably this week. Thank you.

**Comment by jGauravGupta** [comment]
Thanks @senivam,

See https://github.com/eclipse-ee4j/glassfish/issues/23016.
Few blocker dependencies used by Jersey modules which depend on older namespace APIs are:
- Jetty
- BND Http-Service
- Freemarker

ATM In this PR I have disabled those modules as not used by GlassFish.

**Comment by arjantijms** [comment]
Thanks @senivam! That would be much appreciated. For GF the M3 release absolutely doesn't have to be perfect, nor does it have to be in Maven Central. Just a staging is enough.

**Pull request merged**
