### PR TITLE
Issue #4881 - Java client connector

### PR DESCRIPTION
**Pull request by zUniQueX**
Provide a basic implementation of a client connector using java.net.http.HttpClient

Signed-off-by: Steffen Nießing <zuniquex@protonmail.com>

### CODE REVIEW

**Comment by senivam** [comment]
CQs for the PR:
[CQ23888](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23888) - AssertJ
[CQ23889](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23889) - Awaitility

**Comment by zUniQueX** [comment]
@senivam Should I convert the tests to standard assertions? I think AssertJ is more intuitive, but if all other assertions are standard JUnit assertions, I could update to those.

**Comment by senivam** [comment]
@zUniQueX no-no, just leave it as is. Those dependencies will be approved and then your PR will be merged. It's OK, just wait a bit. Thank you :)

**Review by jansupol — APPROVED** [review]

**Comment by jansupol** [comment]
Merged in 2021 to prevent copyright issues

**Comment by senivam** [comment]
related CQs are resolved

**Pull request merged**
