### PR TITLE
Jakartified OSGi tests

### PR DESCRIPTION
**Pull request by senivam**
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

### CODE REVIEW

**Comment by senivam** [comment]
Required:
new Grizzly release which includes relevant OSGi fixes

TODO:
1. Update Grizzly version (after its release)
2. Remove OSGi loggin from helper (left there as WiP change)
3. Remove excluded and commented out redundand OSGi profiles 

Now Build will fail for this PR due to Grizzly dependencies. Shall be re-built after Grizzly release and described fixes.

**Comment by senivam** [comment]
CQ for org.osgi.service.cm (1.5.0) is piggy back from CQ [12385](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12385)

**Comment by jansupol** [comment]
Grizzly 3.0.0 is final now

**Comment by senivam** [comment]
created CQ [22956](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22956)

**Comment by senivam** [comment]
CQ ~~[22956](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22956)~~ resolved

**Review by jansupol — APPROVED** [review]

**Pull request merged**
