### PR TITLE
Prevent NPE in micrometer when there is no response & 404

### LINKED ISSUE #5687: NPE after switching to jersey-micrometer
After upgrading to [Spring Boot 3.3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes) with Micrometer 1.13 I followed the upgrade instructions to add a dependency on `org.glassfish.jersey.ext:jersey-micrometer`

> Micrometer 1.13 has deprecated its Jersey support in favor of Jersey’s jersey-micrometer module. If you application uses Jersey metrics, add a dependency on org.glassfish.jersey.ext:jersey-micrometer when upgrading.

I noticed that after the upgrade, this new library is throwing NPEs from the servlet:

```
2024-07-01T15:52:03,469 [WARN ] (qtp1223917890-76) : ServletChannel - /
jakarta.servlet.ServletException: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "matchingPattern" is null
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:409) ~[jersey-container-servlet-core-3.1.7.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-3.1.7.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) ~[jersey-container-servlet-core-3.1.7.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:312) ~[jersey-container-servlet-core-3.1.7.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-3.1.7.jar:?]
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195) ~[jetty-ee10-websocket-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:317) ~[jetty-ee10-servlets-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:270) ~[jetty-ee10-servlets-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.10.jar:6.1.10]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.10.jar:6.1.10]
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.10.jar:6.1.10]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.10.jar:6.1.10]
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575) ~[jetty-security-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703) ~[jetty-ee10-servlet-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:851) ~[jetty-server-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:597) ~[jetty-server-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:740) ~[jetty-server-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.server.handler.EventsHandler.handle(EventsHandler.java:81) ~[jetty-server-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.server.Server.handle(Server.java:181) ~[jetty-server-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:635) ~[jetty-server-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:403) ~[jetty-server-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322) ~[jetty-io-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99) ~[jetty-io-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979) ~[jetty-util-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209) ~[jetty-util-12.0.10.jar:12.0.10]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164) ~[jetty-util-12.0.10.jar:12.0.10]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "matchingPattern" is null
	at org.glassfish.jersey.micrometer.server.JerseyKeyValues.uri(JerseyKeyValues.java:96) ~[jersey-micrometer-3.1.7.jar:?]
	at org.glassfish.jersey.micrometer.server.DefaultJerseyObservationConvention.getLowCardinalityKeyValues(DefaultJerseyObservationConvention.java:43) ~[jersey-micrometer-3.1.7.jar:?]
	at org.glassfish.jersey.micrometer.server.DefaultJerseyObservationConvention.getLowCardinalityKeyValues(DefaultJerseyObservationConvention.java:30) ~[jersey-micrometer-3.1.7.jar:?]
	at io.micrometer.observation.SimpleObservation.start(SimpleObservation.java:152) ~[micrometer-observation-1.13.1.jar:1.13.1]
	at io.micrometer.observation.docs.ObservationDocumentation.start(ObservationDocumentation.java:241) ~[micrometer-observation-1.13.1.jar:1.13.1]
	at org.glassfish.jersey.micrometer.server.ObservationRequestEventListener.startObservation(ObservationRequestEventListener.java:99) ~[jersey-micrometer-3.1.7.jar:?]
	at org.glassfish.jersey.micrometer.server.ObservationRequestEventListener.onEvent(ObservationRequestEventListener.java:71) ~[jersey-micrometer-3.1.7.jar:?]
	at org.glassfish.jersey.server.internal.monitoring.CompositeRequestEventListener.onEvent(CompositeRequestEventListener.java:47) ~[jersey-server-3.1.7.jar:?]
	at org.glassfish.jersey.server.internal.process.RequestProcessingContext.triggerEvent(RequestProcessingContext.java:203) ~[jersey-server-3.1.7.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:442) ~[jersey-server-3.1.7.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:282) ~[jersey-server-3.1.7.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-3.1.7.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-3.1.7.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-3.1.7.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-3.1.7.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-3.1.7.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266) ~[jersey-common-3.1.7.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:253) ~[jersey-server-3.1.7.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696) ~[jersey-server-3.1.7.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-3.1.7.jar:?]
	... 41 more
```

It seems the library does not handle null values properly and causing unexpected failures during servlet processing. 

Here is the problematic part: https://github.com/eclipse-ee4j/jersey/blob/ed233c5af83901758d1ddc4e9555575c4c66986b/ext/micrometer/src/main/java/org/glassfish/jersey/micrometer/server/JerseyKeyValues.java#L95-L98

```java
        String matchingPattern = JerseyTags.getMatchingPattern(event);
        if (matchingPattern.equals("/")) {
            return URI_ROOT;
        }
```

Where `JerseyTags.getMatchingPattern` is a nullable method, but the return value is not checked and causes NPE at runtime.

### PR DESCRIPTION
**Pull request by jansupol**

### CODE REVIEW

**Comment by zapodot** [comment]
👍🏼

**Comment by jansupol** [comment]
I'd prefer to not squash these 2 commits

**Comment by nioertel** [comment]
👍 
Would love to see this fix in a hopefully soon to be released 3.1.8.

**Review by senivam — APPROVED** [review]

**Review by jbescos — APPROVED** [review]

**Comment by nioertel** [comment]
@senivam, @jbescos I just saw that this PR was against 2.x only. Is there a standard mechanism for forward merging or do you need a separate PR for 3.1?

**Comment by nioertel** [comment]
This is actually a major issue because I am currently working on a quite big REST API that is designed in a way that 404 is considered a "good" response and since upgrade to Spring Boot 3.3.x lots of tests are failing.

Please let me know if I can somehow support so we can maybe get a 3.1.8 release including this fix before end of July.

**Comment by senivam** [comment]
@nioertel uptaking of changes/fixes is done in the order 2.x -> 3.0 -> 3.1 -> 4.0. At least (but might be more often) before a release of a particular version (3.0.x, 3.1.x,...) the previous branch is being merged into the one the release is done from. This ensures all fixes from the prior versions are included in a particular release.

**Pull request merged**
