### PR TITLE
Allow for using HeaderDelegateProvider service 

### PR DESCRIPTION
**Pull request by jansupol**
if CommonProperties#METAINF_SERVICES_LOOKUP_DISABLE is not true

Signed-off-by: Jan Supol <jan.supol@oracle.com>

### CODE REVIEW

**Comment by jansupol** [comment]
fixes #4266

**Comment by pdudits** [comment]
I just noticed that 82a85a1 breaks 'unit' tests `jersey-rest-client-tck`, but the output is quite silent about the actual cause:
```
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.254 s <<< FAILURE! - in org.glassfish.jersey.restclient.ConsumesAndProducesTest
[ERROR] testWithoutEntityActualValue(org.glassfish.jersey.restclient.ConsumesAndProducesTest)  Time elapsed: 3.544 s  <<< ERROR!
javax.ws.rs.WebApplicationException: Unknown error, status code 500
        at org.glassfish.jersey.restclient.ConsumesAndProducesTest.testWithoutEntityActualValue(ConsumesAndProducesTest.java:64)
```
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.065 s <<< FAILURE! - in org.glassfish.jersey.restclient.RestClientModelTest
[ERROR] testGetIt(org.glassfish.jersey.restclient.RestClientModelTest)  Time elapsed: 0.057 s  <<< ERROR!
javax.ws.rs.WebApplicationException: Unknown error, status code 500
        at org.glassfish.jersey.restclient.RestClientModelTest.testGetIt(RestClientModelTest.java:47)
```

**Comment by jansupol** [comment]
I thought the TCK tests are run on Travis

**Comment by jansupol** [comment]
@pdudits the unit tests pass for me with 82a85a1. Are you sure it is this commit that breaks the unit tests? The unit tests are run on Travis just fine.

**Comment by pdudits** [comment]
I'll double check tomorrow. Could also be Windows thing...

**Comment by pdudits** [comment]
Sorry for false alarm, my fault. I was running `mvn -pl :jersey-mp-rest-client -am -amd clean install` and that skips `test-framework`, so I didn't compile all of the changes required for that commit.

**Comment by Verdent** [comment]
That is great to hear :-) I was a bit puzzled why is it not working.

**Pull request merged**
