### PR TITLE
Remove Guava under version 24

### PR DESCRIPTION
**Pull request by jbescos**
- Some dependencies that bring Guava under version 24 have exclusions. Good news is that we only use them for testing/exampling purposes. Lets see if tests are passing with that exclusion.
- With others like testng, just updating the version brings a correct Guava.
- Testng new version works with arquilian-testng in alpha version unfortunately. I hope this is not a problem.

### CODE REVIEW

**Comment by jbescos** [comment]
The build is failing, but when I check the output the maven part is success:

```
[INFO] jersey-examples-moxy ............................... SUCCESS [  2.645 s]
[INFO] jersey-test-framework-maven-custom-enforcer-rules .. SUCCESS [  2.041 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  56:01 min
[INFO] Finished at: 2022-10-12T08:14:29Z
[INFO] ------------------------------------------------------------------------
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // parallel
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
ERROR: script returned exit code 1

GitHub has been notified of this commit’s build result

Finished: FAILURE
```

**Comment by senivam** [comment]
@jbescos build fails for JDK 8 only, here is the log:
https://ci.eclipse.org/jersey/job/continuous-integration/job/PR-5175/7/execution/node/34/log/
the reason is:
```
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/home/jenkins/agent/workspace/continuous-integration_PR-5175/test-framework/core/src/main/java/org/glassfish/jersey/test/JerseyTestNg.java:[27,30] cannot access org.testng.annotations.AfterClass
  bad class file: /home/jenkins/.m2/repository/org/testng/testng/7.6.1/testng-7.6.1.jar(org/testng/annotations/AfterClass.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by jansupol** [comment]
Requirements:
TestNG Upto v7.5: JDK 8 or higher.
TestNG v7.6.0 and above: JDK 11 or higher.
==============================
So we should not go higher than 7.5 in master/3.x

**Comment by jbescos** [comment]
I have tuned the versions to work fine with JDK8 and we also don't need to use an alpha version of arquilian.

**Comment by jbescos** [comment]
These are the guava dependencies that we will have with the fix:

```
$ mvn dependency:tree | grep 'google\.guava'
[INFO] +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] +- com.google.guava:guava:jar:31.1-jre:test
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:test
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:test
[INFO] +- com.google.guava:guava:jar:31.1-jre:test
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:test
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:test
[INFO] |  |  \- com.google.guava:guava:jar:25.1-android:compile
[INFO] +- com.google.guava:guava:jar:31.1-jre:test
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:test
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:test
[INFO] +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  \- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |     +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |     +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
```

This is what we have now in master:

```
$ mvn dependency:tree | grep 'google\.guava'
[INFO] |  |  \- com.google.guava:guava:jar:16.0.1:provided
[INFO] |  \- com.google.guava:guava:jar:16.0.1:compile
[INFO] +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |     \- com.google.guava:guava:jar:16.0.1:test
[INFO] |     \- com.google.guava:guava:jar:16.0.1:test
[INFO] |     \- com.google.guava:guava:jar:16.0.1:test
[INFO] |     \- com.google.guava:guava:jar:16.0.1:test
[INFO] |  |  \- com.google.guava:guava:jar:16.0.1:test
[INFO] |  +- com.google.guava:guava:jar:20.0:test
[INFO] +- com.google.guava:guava:jar:31.1-jre:test
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:test
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:test
[INFO] |  |  \- com.google.guava:guava:jar:16.0.1:test
[INFO] |  |  \- com.google.guava:guava:jar:25.1-android:compile
[INFO] +- com.google.guava:guava:jar:31.1-jre:test
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:test
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:test
[INFO] |     +- com.google.guava:guava:jar:16.0.1:compile
[INFO] |  \- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |     +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |     +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile

```

**Review by jansupol — APPROVED** [review]

**Review by senivam — APPROVED** [review]

**Pull request merged**
