### PR TITLE
Added client support for ConnectionKeepAliveStrategy and ConnectionReuseStrategy

### PR DESCRIPTION
**Pull request by rsandidfc**
Added client support for ConnectionKeepAliveStrategy and ConnectionReuseStrategy

Signed-off-by: Richard A Sand <rsand@idfconnect.com>

### CODE REVIEW

**Comment by jansupol** [comment]
Unlike the #4195, this has a valid ECA, Confirmed with ECA VALIDATION TOOL: 
> There is a valid ECA on file for rsand@idfconnect.com.

- Copyright year is not updated

**Comment by jansupol** [comment]
Checkstyle: (blocks) NeedBraces: 'if' construct must use '{}'s.

**Comment by jansupol** [comment]
Hi @rsandidfc, Thanks for contributing. This looks good. There is quite a number of possibilities that can be set using the

**Comment by rsandidfc** [comment]
Thanks, I submitted a new pull request with the {} fixed for checkstyle to pass

**Pull request closed without merging**
