### PR TITLE
#3700: Treat resource instances as resources.

### PR DESCRIPTION
**Pull request by objecttrouve**
Cosmetic elimination of a warning. 

The intuition is that if resource classes are OK, resource instances should be, too. 

The predicate that tells if a component class is `correctlyConfigured` only checked the `resourceClasses` collection to determine whether the resource is actually a resource.
As a consequence a warning, was logged when an _instantiated_ resource class was tested:

`WARNING: A provider war.HelloWorldResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider war.HelloWorldResource will be ignored.
`

The change is as conservative as possible.
Changed the result of the relevant predicate only in the context where the changed result values should not have any impact.
But the side-effect of logging a warning should go away.

No additional test since the change shouldn't have any observable effect other than the absence of a warning.

### CODE REVIEW

**Comment by jansupol** [comment]
References #3700

**Comment by serhiypal** [comment]
It is not an intuition it is a regression in the logic. This block https://github.com/jersey/jersey/blob/2.25.1/core-server/src/main/java/org/glassfish/jersey/server/ApplicationHandler.java#L982 was not ported over to `2.27`.

**Comment by senivam** [comment]
please do not use instance registration to register resource instances without any additional container implementation. I was explaining difference between instance and class registrations (they are really not the same) in bug #3700 and in PR #3918 the warning is thrown intentionally and there is no need to fix that.

**Comment by objecttrouve** [comment]
Thanks for the clarification. Closing the request.

**Pull request closed without merging**
