### PR TITLE
Adopt Jackson 2.10.1

### PR DESCRIPTION
**Pull request by jansupol**

### CODE REVIEW

**Comment by jansupol** [comment]
Fixes #4308

**Comment by jansupol** [comment]
Filed CQs:
- [~21237~](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=21237) jackson-core
- [~21238~](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=21238) jackson-databind
- [~21280~](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=21280) jackson-annotations
- [~21281~](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=21281) jackson-jaxrs-provider
- [~21282~](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=21282) jackson-jaxrs-base
- [21283](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=21283) jackson-jaxrs-providers-repackaged
- [~21284~](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=21284) jackson-module-jaxb-annotations

**Comment by alex1989hu** [comment]
@jansupol: a newer version has been released: **2.10.2**. Is it possible to update your PR with that version? [Patch version of 2.10, released on 05-Jan-2020](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10.2)

**Comment by jansupol** [comment]
@alex1989hu Maybe. We would need to file new CQs. But the old CQ has not been approved, yet.

**Comment by jansupol** [comment]
The CQ has been approved. I think for 2.30.1 we can go with this one. 

@alex1989hu 
Does the new Jackson have some new features for which it would be preferred? You may always replace the dependencies with the latest in your pom files.

**Comment by alex1989hu** [comment]
> The CQ has been approved. I think for 2.30.1 we can go with this one.
> 
> @alex1989hu
> Does the new Jackson have some new features for which it would be preferred? You may always replace the dependencies with the latest in your pom files.

Hello, those are fixes  *- a patch release -*, see the referenced URL in https://github.com/eclipse-ee4j/jersey/pull/4339#issuecomment-574093781

**Pull request merged**
