### PR TITLE
 Upgrade Netty and expose Netty Context

### PR DESCRIPTION
**Pull request by juur**
Bumped netty version to latest
Updated API usage to match
Enhanced returned SecurityContext to include Netty information

### CODE REVIEW

**Comment by jansupol** [comment]
There is a valid ECA on file for eclipse@wut.to.

**Comment by juur** [comment]
Does the CQ required label require me to do anything?

**Comment by jansupol** [comment]
No, I think only committers can file CQs. Once Jersey goes through release review, we will deal with new CQs

**Comment by mkarg** [comment]
@jansupol FYI I just tested it, and you are right: The Eclipse Committer Tools present a 404 to me when trying to file a CQ for Jersey, while it works for JAX-RS. So this is definitively a committers-only task.

**Comment by jansupol** [comment]
Created [CQ for Netty 4.1.31.FINAL](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19281)

**Comment by jansupol** [comment]
CQ has been approved.

**Comment by rvowles** [comment]
Netty is still unusable because of #3500

**Pull request merged**
