### PR TITLE
Fixes #3997 : Make SupplierFactoryBridge thread-safe.

### LINKED ISSUE #3997: SupplierFactoryBridge#provide can cause race condition (running the CPU at 100%)
The disposableSuppliers field of SupplierFactoryBridge is not synchronized.

When many threads use instances supplied by DisposableSupplier, The SupplierFactoryBridge#provide invokes IdentityHashMap#put, which is not thread safe, concurrently and can cause race condition.

### PR DESCRIPTION
**Pull request by hypnoce**
Based on https://github.com/eclipse-ee4j/jersey/pull/4000

### CODE REVIEW

**Comment by hypnoce** [comment]
Some jobs have failed on travis. Seems that they are not related to the changes. Can you confirm ?

**Comment by jansupol** [comment]
[This](https://travis-ci.community/t/cannot-install-oracle-jdk-11/3892) seems to be the most recent bug for this issue. My feeling from the bug is Travis is going to remove the Oracle JDK support. The solution can be to switch to OpenJDK11 if the issue is not resolved next week.

**Comment by jansupol** [comment]
The Travis issues are being solved in #4180

**Comment by hypnoce** [comment]
I will wait for your PR to be merged, and then rebase mine.

**Comment by hypnoce** [comment]
The build has passed. I steer anything to change in this PR ?

**Comment by hypnoce** [comment]
@jansupol is there anything preventing this PR to be merged ?

**Comment by jansupol** [comment]
@hypnoce Can you please update copyright year?

**Comment by hypnoce** [comment]
@jansupol done !

**Comment by hypnoce** [comment]
Apparently there was an OOM on the CI

**Pull request merged**
