### PR TITLE
Fix priority ordering

### PR DESCRIPTION
**Pull request by jansupol**
Signed-off-by: Jan Supol <jan.supol@oracle.com>

### CODE REVIEW

**Comment by jansupol** [comment]
Fixes #4099.

**Comment by senivam** [comment]
@chkal I suppose, it should be vice versa. As soon as #4101 is ignored for now and will be valid only after this PR is merged. So this goes first and then #4101 without @Ignore

**Comment by chkal** [comment]
Ok, sure! I'll update #4101 and remove the `@Ignore` as soon as this PR is merged! Thanks a lot for your help.

**Comment by jansupol** [comment]
@chkal Please remove `@Ignore`. Thank you for the very nice test case.

**Comment by chkal** [comment]
I just updated #4101 as requested. I hope the test case was useful for reproducing the issue.

**Pull request merged**
