### PR TITLE
Create HTTPS tests with JNH connector #5169

### PR DESCRIPTION
**Pull request by jbescos**
Relates to https://github.com/eclipse-ee4j/jersey/issues/5169

Test passes successfully.

### CODE REVIEW

**Review by jansupol — APPROVED** [review]

**Comment by jbescos** [comment]
I think I need to rebase it from master and change some junit imports

**Comment by jansupol** [comment]
There would be more PRs like that, we can fix it later, or you can fix it if you want

**Comment by jbescos** [comment]
I will do it in all my PRs now, so there will be less work to do later

**Comment by jbescos** [comment]
I am going to leave it as it is, because there are many conflicts coming from classes that I didn't touch

**Pull request merged**
