### PR TITLE
Spring 6 module introduction

### PR DESCRIPTION
**Pull request by jansupol**
Signed-off-by: jansupol <jan.supol@oracle.com>

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks, @jansupol. I've been trying to get Spring Boot working against a local build of your branch. One thing that tripped me up was the [javaPre17 variant https://github.com/jansupol/jersey/blob/34a869b8cc5daf679eece807a5bdab1780fc21af/ext/spring6/src/main/javaPre17/org/glassfish/jersey/server/spring/SpringComponentProvider.java] of `SpringComponentProvder` was being used instead of [the java17 variant](https://github.com/jansupol/jersey/blob/34a869b8cc5daf679eece807a5bdab1780fc21af/ext/spring6/src/main/java17/org/glassfish/jersey/server/spring/SpringComponentProvider.java). As a result any Spring-managed beans were not available to Jersey as they should be. I think this was because I ran my local build (`mvn -DskipTests=true clean install`) with Java 8. Running it again with Java 17 resulted in a failure:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  47.955 s
[INFO] Finished at: 2022-04-04T21:18:19+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project jersey-media-sse: Compilation failure: Compilation failure: 
[ERROR] /Users/awilkinson/dev/eclipse-ee4j/jersey/media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:[34,44] cannot find symbol
[ERROR]   symbol:   class JerseyFlowSubscriber
[ERROR]   location: package org.glassfish.jersey.internal.jsr166
[ERROR] /Users/awilkinson/dev/eclipse-ee4j/jersey/media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:[48,45] cannot find symbol
[ERROR]   symbol: class JerseyFlowSubscriber
[ERROR] /Users/awilkinson/dev/eclipse-ee4j/jersey/media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:[60,5] method does not override or implement a method from a supertype
[ERROR] /Users/awilkinson/dev/eclipse-ee4j/jersey/media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:[79,5] method does not override or implement a method from a supertype
[ERROR] /Users/awilkinson/dev/eclipse-ee4j/jersey/media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:[105,5] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
```

I then tried just building the `spring6` module `mvn -f ext/spring6 -DskipTests=true clean install` and that seems to have fixed the problem. I suspect this is user error in how I built the project, but wanted to mention it just in case.

**Comment by wilkinsona** [comment]
Thanks, @jansupol. I've been trying to get Spring Boot working against a local build of your branch. One thing that tripped me up was the [javaPre17 variant https://github.com/jansupol/jersey/blob/34a869b8cc5daf679eece807a5bdab1780fc21af/ext/spring6/src/main/javaPre17/org/glassfish/jersey/server/spring/SpringComponentProvider.java] of `SpringComponentProvder` was being used instead of [the java17 variant](https://github.com/jansupol/jersey/blob/34a869b8cc5daf679eece807a5bdab1780fc21af/ext/spring6/src/main/java17/org/glassfish/jersey/server/spring/SpringComponentProvider.java). As a result any Spring-managed beans were not available to Jersey as they should be. I think this was because I ran my local build (`mvn -DskipTests=true clean install`) with Java 8. Running it again with Java 17 resulted in a failure:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  47.955 s
[INFO] Finished at: 2022-04-04T21:18:19+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project jersey-media-sse: Compilation failure: Compilation failure: 
[ERROR] /Users/awilkinson/dev/eclipse-ee4j/jersey/media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:[34,44] cannot find symbol
[ERROR]   symbol:   class JerseyFlowSubscriber
[ERROR]   location: package org.glassfish.jersey.internal.jsr166
[ERROR] /Users/awilkinson/dev/eclipse-ee4j/jersey/media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:[48,45] cannot find symbol
[ERROR]   symbol: class JerseyFlowSubscriber
[ERROR] /Users/awilkinson/dev/eclipse-ee4j/jersey/media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:[60,5] method does not override or implement a method from a supertype
[ERROR] /Users/awilkinson/dev/eclipse-ee4j/jersey/media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:[79,5] method does not override or implement a method from a supertype
[ERROR] /Users/awilkinson/dev/eclipse-ee4j/jersey/media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:[105,5] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
```

I then tried just building the `spring6` module `mvn -f ext/spring6 -DskipTests=true clean install` and that seems to have fixed the problem. I suspect this is user error in how I built the project, but wanted to mention it just in case.

**Comment by wilkinsona** [comment]
Thanks again, @jansupol. Once I had got the Jersey snapshot built correctly, I was able to get clean build of Spring Boot with its Jersey support reinstated. The changes proposed here look good to me.

**Comment by jansupol** [comment]
Created CQs:

- [Spring AOP](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24019)
- [Spring beans](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24020)
- [Spring core](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24021)
- [Spring Context](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24022)
- [Spring Web](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24023)

**Comment by jansupol** [comment]
The CQs are resolved.

**Review by senivam — APPROVED** [review]
LGTM

**Comment by wilkinsona** [comment]
@jansupol Spring Framework 6 and Spring Boot 3 will have a Jakarta EE 9 (JAX-RS 3.0) baseline. Would it be possible for the new `jersey-spring6` module to be included in a Jersey release that supports JAX-RS 3.0?

**Comment by jansupol** [comment]
@wilkinsona  Yes. Jersey 3.0.5 is planned to contain the module. We plan the release at the end of this month.

**Comment by wilkinsona** [comment]
That's great. Thanks very much once again.

**Pull request merged**
