### PR TITLE
Micrometer - Add missing metrics for cases of client errors

### PR DESCRIPTION
**Pull request by adpaste**
Changes ported from https://github.com/micrometer-metrics/micrometer/pull/4326

### CODE REVIEW

**Comment by senivam** [comment]
Thank you for the PR. Will the #5531 be fixed either?

**Comment by adpaste** [comment]
No problem! https://github.com/eclipse-ee4j/jersey/issues/5531 is a different issue.

**Comment by senivam** [comment]
> No problem! #5531 is a different issue.

yes, I'm just reminding in order not to forget about it :)

**Review by jansupol — APPROVED** [review]

**Review by senivam — APPROVED** [review]

**Comment by andersflemmen** [comment]
Any chance for this fix to be ported to the 3.x version as well? We are actually seeing NullPointerExceptions caused by matchingPattern being null when making a request to a non-existing URL.

**Comment by senivam** [comment]
@andersflemmen it should already be there, all fixes in the 2.x are later uptaken by 3.0, 3.1 etc.

**Comment by andersflemmen** [comment]
Sorry, the error actually occurs in the JerseyKeyValues class. Seems like that one had a similar fix in the micrometer repo:
https://github.com/micrometer-metrics/micrometer/commit/66c1d4772019146b47ac27e4bcdd324000cedc7f

```
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "matchingPattern" is null
        at org.glassfish.jersey.micrometer.server.JerseyKeyValues.uri(JerseyKeyValues.java:96)
        at org.glassfish.jersey.micrometer.server.DefaultJerseyObservationConvention.getLowCardinalityKeyValues(DefaultJerseyObservationConvention.java:43)
        at org.glassfish.jersey.micrometer.server.DefaultJerseyObservationConvention.getLowCardinalityKeyValues(DefaultJerseyObservationConvention.java:30)
        at io.micrometer.observation.SimpleObservation.start(SimpleObservation.java:152)
        at io.micrometer.observation.docs.ObservationDocumentation.start(ObservationDocumentation.java:241)
        at org.glassfish.jersey.micrometer.server.ObservationRequestEventListener.startObservation(ObservationRequestEventListener.java:99)
        at org.glassfish.jersey.micrometer.server.ObservationRequestEventListener.onEvent(ObservationRequestEventListener.java:71)
        at org.glassfish.jersey.server.internal.monitoring.CompositeRequestEventListener.onEvent(CompositeRequestEventListener.java:47)
        at org.glassfish.jersey.server.internal.process.RequestProcessingContext.triggerEvent(RequestProcessingContext.java:203)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:442)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:282)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:253)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
        ... 128 common frames omitted
```

**Comment by jansupol** [comment]
@andersflemmen I have it backported in #5690

**Pull request merged**
